#!/bin/bash
#
# authors:    Victor Golovachenko
#

SCRIPT_NAME=`basename "$0"`

DEV=/dev/spidev2.0
APP=./app_fpga_ddr_v2

TEST_FILE=./test_data
READ_PEFIX=_rr
VERBOSE=16384
TEST_SIZE=8

if [ -n "$1" ]; then
    if [ "$1" == "-h" ]; then
        echo "Usage: ./$SCRIPT_NAME [option]";
        echo "Mandatory option:";
        echo "    -h           help";
        echo "    -s  <value>  size(MB)";
        echo "";
        echo "Example using:";
        echo "    ./$SCRIPT_NAME -s 64;"
        echo "";
        exit 0
    else
        if [ "$1" == "-s" ]; then
            if [ -n "$2" ]; then
                TEST_SIZE=$2
            else
                echo "Bad argument: try -h"
                exit 1
            fi
        else
            echo "Bad argument: try -h"
            exit 1
        fi
    fi
else
    echo "Bad argument: try -h"
    exit 1
fi



if [ -f  $TEST_FILE ]; then
    rm $TEST_FILE
fi

if [ -f  $TEST_FILE$READ_PEFIX ]; then
    rm $TEST_FILE$READ_PEFIX
fi

echo " "
echo "******************************"
echo "Generate test data"
echo "******************************"
dd if=/dev/urandom of=$TEST_FILE bs=1048576 count=$TEST_SIZE || exit 1

FILENAME=$(stat -c%n "$TEST_FILE")
FILESIZE=$(stat -c%s "$TEST_FILE")
printf -v FILESIZE_hex '%x' $FILESIZE
echo "$FILENAME size: $FILESIZE (x$FILESIZE_hex)"


echo " "
echo "******************************"
echo "Write sata to DDR"
echo "******************************"
$APP -d $DEV -v $VERBOSE  --addr 0x00 --wdata 0 $TEST_FILE || exit 1

echo " "
echo "******************************"
echo "Read data from DDR"
echo "******************************"
$APP -d $DEV -v $VERBOSE --addr 0x00 --rdata 0x$FILESIZE_hex $TEST_FILE$READ_PEFIX || exit 1


echo " "
echo "******************************"
echo "Compare"
echo "******************************"
diff ./$TEST_FILE ./$TEST_FILE_rr || exit 1

echo " "
echo "test passed"

if [ -f  $TEST_FILE ]; then
    rm $TEST_FILE
fi

if [ -f  $TEST_FILE$READ_PEFIX ]; then
    rm $TEST_FILE$READ_PEFIX
fi